In [5]:
import numpy as np 


#normal list
a = ["0", 1, "two", "3", 4]
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])
print(type(a))

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4
<class 'list'>


In [8]:
a=np.array(["0", 1, "two", "3", 4])
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])
print(type(a))
a.dtype

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4
<class 'numpy.ndarray'>


dtype('<U11')

In [9]:
a[0] = 100
a[-1] = 200
a

array(['100', '1', 'two', '3', '200'], dtype='<U11')

In [11]:
b = a[2:] # slicing
b

array(['two', '3', '200'], dtype='<U11')

In [15]:
b.size

3

In [16]:
b.ndim

1

In [17]:
b.shape

(3,)

### other functions


In [21]:
a = np.array([2, -1, 1, -1])

In [22]:
mean = a.mean()
mean

0.25

In [23]:
stddeviation = a.std()
stddeviation

1.299038105676658

In [24]:
a.max()

2

In [25]:
a.min()

-1

## Numpy Array Operations

In [26]:
u = np.array([1, 0])
u

array([1, 0])

In [27]:
v = np.array([0, 1])
v

array([0, 1])

In [28]:
z = u + v # Addition
z

array([1, 1])

In [30]:
z = u*v # product of two arrays
z

array([0, 0])

In [31]:
z = 2*u # multiplication
z

array([2, 0])

In [32]:
np.dot(u,v) # dot product

0

In [33]:
z = u+3 # adding a constant
z

array([4, 3])

In [34]:
np.pi

3.141592653589793

### 2D numpy array

In [35]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [37]:
aa = np.array(a)
aa

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [38]:
aa.size

9

In [39]:
aa.ndim

2

In [40]:
aa.shape

(3, 3)

In [41]:
aa[2,0]

31

In [42]:
aa[0,0]

11

In [44]:
aa[2][2]

33

In [46]:
aa[1][0:2]

array([21, 22])

In [47]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [48]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [49]:
Z = X+Y # ADDING 2D ARRAY
Z

array([[3, 1],
       [1, 3]])

In [51]:
Z = 3*Y # MULTIPLYING CONSTANT
Z

array([[6, 3],
       [3, 6]])

In [52]:
Z= X*Y # PRODUCT
Z

array([[2, 0],
       [0, 2]])

In [57]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)  

0

In [56]:

X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])